config/routes.rb
Rails.application.routes.draw do
  resources :doctors
  resources :hospitals do
      post 'remove_doctor', on: :member
  end    

  root 'hospitals#index'


end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
end

app/models/hospital.rb
class Hospital < ActiveRecord::Base
	attr_accessor :doctors_list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show]


  def index
    @doctors = Doctor.all
  end

  def show
  end


  private


  def set_doctor
    @doctor = DoctorDecorator.decorate(Doctor.find(params[:id]))
  end

end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  before_action :set_hospital, only: [:show, :edit, :update, :remove_doctor]


  def index
    @hospitals = Hospital.all
  end

  def edit
  end

  def update
    notice = SHospital::Update.new(@hospital, params).main
    respond_to do |format|
      if @hospital.save
        format.html { redirect_to :back, notice: notice }
      end
    end
  end

  def remove_doctor
    notice = SHospital::RemoveDoctor.new(@hospital, params).main
    respond_to do |format|
      if @hospital.save
        format.html { redirect_to :back, notice: notice }
      end
    end
  end


  private


  def set_hospital
    @hospital = HospitalDecorator.decorate(Hospital.find(params[:id]))
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/views/doctors/index.html.erb
<h1>Все врачи</h1>

<table>
  <thead>
    <tr>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.id %></td>
        <td><%= link_to  doctor.name, doctor_path(doctor) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Все больницы', '/hospitals' %>

app/views/doctors/show.html.erb
<h1><%= @doctor.name %></h1>
<i>Режим просмотра</i><br/>

<h4>Список больниц, в которых работает этот доктор</h4>
<table>
	<tr>
	  <td>Имя</td>
	  <td>Действие</td>
	</tr>
	<% @doctor.has_hospitals.each do |element| %>
	<tr>
	  <td><%= element.name  %></td>
	  <td><%= link_to "посмотреть", edit_hospital_path(element) %></td>
	</tr>
	<% end %>
</table>
<hr/>

<%= link_to 'К списку больниц', hospitals_path %>
<%= link_to 'К списку докторов', hospitals_path %>

app/views/hospitals/edit.html.erb
<h1><%= @hospital.name %></h1>
<i>Режим редактирования</i><br/>
<i><%= flash[:notice] %></i>

<table>
	<tr>
	  <td>Имя</td>
	  <td>Действие</td>
	</tr>
	<% @hospital.personal.each do |element| %>
	<tr>
	  <td><%= link_to element.name, doctor_path(element) %></td>
	  <td><%= button_to "Удалить",{action: "remove_doctor", doctor_id: element.id} %></td>
	</tr>
	<% end %>
</table>
<hr/>
<table>
<%= form_for(@hospital) do |f| %>
	<tr>
	  <td><%= f.select(:doctors_list, options_for_select(@hospital.avaible_doctors), {include_blank: "Не выбрано", include_hidden: false}) %></td>
	  <td><%= f.submit "Добавить" %></td>
	</tr>
<% end %>	
</table>

<%= link_to 'Назад', @hospital %> |
<%= link_to 'К списку больниц', hospitals_path %>

app/views/hospitals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Все больницы</h1>

<table>
  <thead>
    <tr>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @hospitals.each do |hospital| %>
      <tr>
        <td><%= hospital.id %></td>
        <td><%=  hospital.name %></td>
        <td><%= link_to 'Редактировать', edit_hospital_path(hospital) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Все врачи', '/doctors' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SimpleApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>